server:
  port: 9401
spring:
  profiles:
    active: dev
  application:
    name: datacenter-auth2-service
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
#  redis:
#    database: 0
#    port: 6379
#    host: localhost
#    password: 12345
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5432/user_db
    username: sensorweb
    password: 12345
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sensorweb.datacenterauth2service.entity
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true
management:
  endpoints:
    web:
      exposure:
        include: "*"

# eureka注册中心
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/